In [15]:
import multiprocess as mp
import numpy as np
from time import sleep

In [116]:
total_timesteps = len(np.arange(0,8760,1))
ncpu = 6


def create_timestep_chunks(total_timesteps, ncpu):
    incre = int(total_timesteps/ncpu)
    incre_range = range(0,total_timesteps,incre)
    incre_chunks = [np.arange(i,i+incre) for i in incre_range]

    return incre_chunks

create_timestep_chunks(total_timesteps, 6)

[array([   0,    1,    2, ..., 1457, 1458, 1459]),
 array([1460, 1461, 1462, ..., 2917, 2918, 2919]),
 array([2920, 2921, 2922, ..., 4377, 4378, 4379]),
 array([4380, 4381, 4382, ..., 5837, 5838, 5839]),
 array([5840, 5841, 5842, ..., 7297, 7298, 7299]),
 array([7300, 7301, 7302, ..., 8757, 8758, 8759])]

In [19]:
def create_sample_dict():
    s = {
        "OBJECT": {
            "SRF1": {
                "RESULTS": {"A": {},
                            "B": {}},
                "STRING1": {
                    "RESULTS": {"A": {},
                                "B": {}},
                    "MODULE1": {
                        "RESULTS": {"A": {},
                                    "B": {}},
                    },
                    "MODULE2": {
                        "RESULTS": {"A": {},
                                    "B": {}},  
                    },
                },
                "STRING2": {
                    "RESULTS": {"A": {},
                                "B": {}},
                    "MODULE1": {
                        "RESULTS": {"A": {},
                                    "B": {}},
                    },
                    "MODULE2": {
                        "RESULTS": {"A": {},
                                    "B": {}},  
                    },
                }
            },
            "SRF2": {
                "RESULTS": {"A": {},
                            "B": {}},
                "STRING1": {
                    "RESULTS": {"A": {},
                                "B": {}},
                    "MODULE1": {
                        "RESULTS": {"A": {},
                                    "B": {}},
                    },
                    "MODULE2": {
                        "RESULTS": {"A": {},
                                    "B": {}},  
                    },
                },
                "STRING2": {
                    "RESULTS": {"A": {},
                                "B": {}},
                    "MODULE1": {
                        "RESULTS": {"A": {},
                                    "B": {}},
                    },
                    "MODULE2": {
                        "RESULTS": {"A": {},
                                    "B": {}},  
                    },
                }
            },
        }
    }
    return s


In [130]:
def main_sim(hoy):
    results_hoy1 = {hoy: np.arange(1,10,1)}
    results_hoy2 = {hoy: np.arange(0,1,.1)}
    results_hoy3 = {hoy: np.arange(5,50,5)}
    return results_hoy1, results_hoy2, results_hoy3

def wrap_loop(hoy_chunk):
    A_list = {}
    B_list = {}
    C_list = {}
    for hoy in hoy_chunk:
        sleep(0.05)
        A,B,C = main_sim(hoy)
        A_list.update(A)
        B_list.update(B)
        C_list.update(C)
    return A_list,B_list,C_list
    
def mp_hoy():
    total_timesteps = len(np.arange(0,1000,1))
    chunks = create_timestep_chunks(total_timesteps, 6)
    pool = mp.Pool(6)
    result = pool.map(wrap_loop, chunks)
    pool.close()
    return result

    

In [ ]:
def mp_simulation_wrapper():
    modules_i_dict = {}
    modules_v_dict = {}
    modules_g_dict = {}
    
    for hoy in hoy_chunk:
        Imod, Vmod, Gmod = simulation_module_yield(panelizer_object, surface, string, module, hoy)
        modules_i_dict.update({hoy:Imod})
        modules_v_dict.update({hoy:Vmod})
        modules_g_dict.update({hoy:Gmod})
        
    return modules_i_dict, modules_v_dict, modules_g_dict
    
def run_mp_simulation():
    total_timesteps = len(np.arange(0,1000,1))
    chunks = create_timestep_chunks(total_timesteps, 6)
    pool = mp.Pool(6)
    result = pool.map(wrap_loop, chunks)
    pool.close()
    return result
    

def loop_module_simulation(panelizer_object, surface, string, hoy):
    # modules_i = []
    # modules_v = []
    # modules_g = []
    for module in panelizer_object.get_modules(surface, string):
        # chunk hoy here and MP the module simulation
        # write back to a dict for Imod, VMod, and input_energy
        
        mp_result = run_mp_simulation()

        for hoy in all_hoy:
            Imod = mp_result[0]
            Vmod = mp_result[1]
            Gmod = mp_result[2]
            
            panelizer_object.get_dict_instance([surface, string, module])['YIELD'][panelizer_object.topology][
                'irrad'].update({hoy: np.round(Gmod, 1)})
            panelizer_object.get_dict_instance([surface, string, module])['CURVES'][panelizer_object.topology][
                'Imod'].update({hoy: np.round(Imod, 3)})
            panelizer_object.get_dict_instance([surface, string, module])['CURVES'][panelizer_object.topology][
                'Vmod'].update({hoy: np.round(Vmod, 3)})

    # return modules_i, modules_v, modules_g

[(0, 1460),
 (1460, 2920),
 (2920, 4380),
 (4380, 5840),
 (5840, 7300),
 (7300, 8760)]

In [131]:

main_dict = {"A_list":{},
             "B_list":{},
             "C_list":{}}

r = mp_hoy()

for r_ in r:
    main_dict["A_list"].update(r_[0])
    main_dict["B_list"].update(r_[1])
    main_dict["C_list"].update(r_[2])

In [132]:
main_dict = {"A_list":{},
             "B_list":{},
             "C_list":{}}

r = wrap_loop(np.arange(0,1000,1))

main_dict["A_list"].update(r[0])
main_dict["B_list"].update(r[1])
main_dict["C_list"].update(r[2])

In [67]:


class A:
    def __init__(self, *args, **kwargs):
        # do other stuff
        self.object_dict = create_sample_dict()
        self.topology = None
        self.surface = None
        self.string = None
        self.ncpu = 6

    def mp_run(self):
        chunks = create_timestep_chunks(total_timesteps, self.ncpu)
        
        for topo in ["A", "B"]:
            self.topology = topo
            for srf in ["SRF1","SRF2"]:
                self.surface = srf
                for str in ["STRING1", "STRING2"]:
                    self.string = str
                    pool = mp.Pool(self.ncpu)
                    pool.map(self.do_something, chunks)
                    pool.close()

    
    def do_something(self, chunk):
        for module in ["MODULE1", "MODULE2"]:
            for hoy in np.arange(chunk[0],chunk[1]):
                sub_dict = self.object_dict["OBJECT"][self.surface][self.string][module]['RESULTS'][self.topology]
                sub_dict.update({hoy:{"first":hoy,
                                    "second":hoy*2,
                                    "third":hoy**2}
                                }
                                )
                
                
    
    # def sim(self):
    #     srf_dict = self.object_dict[self.srf]
    #     for string in ["STRING1", "STRING2"]:
            
            
        
        



In [65]:
def loop(obj):
    total_timesteps = len(np.arange(0,24,1))
    chunks = create_timestep_chunks(total_timesteps, obj.ncpu)
    
    for topo in ["A", "B"]:
        obj.topology = topo
        for srf in ["SRF1","SRF2"]:
            obj.surface = srf
            for str in ["STRING1", "STRING2"]:
                obj.string = str
                for chunk in chunks:
                    obj.do_something(chunk)
                # mp_run(obj, chunks)
                
                
def mp_run(obj,chunks):
    pool = mp.Pool(obj.ncpu)
    pool.map(obj.do_something, chunks)
    pool.close()
    print(obj.object_dict["OBJECT"][obj.surface][obj.string]["MODULE1"]['RESULTS']["A"])

In [57]:
total_timesteps = len(np.arange(0,24,1))
for c in create_timestep_chunks(total_timesteps, 6):
    for h in np.arange(c[0],c[1]):
        print(h)

TypeError: 'tuple' object cannot be interpreted as an integer

In [70]:

a = A()
loop(a)

In [69]:
a.object_dict["OBJECT"][a.surface][a.string]["MODULE1"]['RESULTS']["A"] = 90

In [71]:
a.object_dict

{'OBJECT': {'SRF1': {'RESULTS': {'A': {}, 'B': {}},
   'STRING1': {'RESULTS': {'A': {}, 'B': {}},
    'MODULE1': {'RESULTS': {'A': {0: {'first': 0, 'second': 0, 'third': 0},
       1: {'first': 1, 'second': 2, 'third': 1},
       2: {'first': 2, 'second': 4, 'third': 4},
       3: {'first': 3, 'second': 6, 'third': 9},
       4: {'first': 4, 'second': 8, 'third': 16},
       5: {'first': 5, 'second': 10, 'third': 25},
       6: {'first': 6, 'second': 12, 'third': 36},
       7: {'first': 7, 'second': 14, 'third': 49},
       8: {'first': 8, 'second': 16, 'third': 64},
       9: {'first': 9, 'second': 18, 'third': 81},
       10: {'first': 10, 'second': 20, 'third': 100},
       11: {'first': 11, 'second': 22, 'third': 121},
       12: {'first': 12, 'second': 24, 'third': 144},
       13: {'first': 13, 'second': 26, 'third': 169},
       14: {'first': 14, 'second': 28, 'third': 196},
       15: {'first': 15, 'second': 30, 'third': 225},
       16: {'first': 16, 'second': 32, 'third': 25